added feature: search user using name
StressedByAThousandCodes/spotify-clone pull request #5
Opened 2023-03-09 06:33 UTC by StressedByAThousandCodes

2023-03-09 08:12 UTC, carl-howell approved these changes

2023-03-10 01:11 UTC, carlofurio-swr requested changes

2023-03-10 01:11 UTC, carlofurio-swr commented on src/user/user.controller.ts
> +
remove these extra spaces.

2023-03-10 01:11 UTC, carlofurio-swr commented on src/user/user.service.ts
remove these extra spaces

2023-03-10 01:15 UTC, mika-ella commented on src/user/user.controller.ts
> +  findUserByName(@Body() body: any) {
create type for body

2023-03-10 01:15 UTC, mika-ella commented on src/user/user.controller.ts
> +  findUserByName(@Body() body: any) {
can this be a params? not a body

2023-03-10 01:22 UTC, StressedByAThousandCodes commented on src/user/user.controller.ts
> +  findUserByName(@Body() body: any) {
there is an existing same function that has a params
@UseGuards(AuthGuard('jwt'))
  @Get(':id')
  findOneUser(@Param('id') id: number) {
    return this.userService.findUser(id);
  }

2023-03-10 01:50 UTC, mika-ella approved these changes

2023-03-10 01:50 UTC, merged